name: linter
on: [push, pull_request]

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    strategy:
      matrix:
        go-version: [1.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3

      - name: golangci-lint ${{ matrix.working-directory }}
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --verbose
