name: test
on:
  push:
    branches:
    - master
  pull-request:
    branches:
    - master

permissions:
  contents: read

jobs:
  unit:
    strategy:
      matrix:
        go-version: [1.x]
        platform: [ubuntu-latest]
    name: unit
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          
      - name: Run go test
        run: go test -v -race -coverprofile coverage.out -covermode atomic ./...
